/* 	Jenney Grover
	MIU 1307
	Your Personal Librarian
	Project 1, 2, 3, 4
	began June 7, 2013
	
	20 sample books
*/

var json = {
	"book1": {
		nameBook 	: ["Name: ", "To Kill a Mockingbird"],
		nameAuthor 	: ["Author: ", "Harper Lee"],
		isbnNumber 	: ["ISBN: ", "9780397001514"],
		dateAdded 	: ["Added: ", "06-13-2010"],
		datePublish : ["Published: ", "1988"],
		genre		: ["Genre: ", "drama"],
		readBook	: ["Read: ", "unread"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "mobile"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book2": {
		nameBook 	: ["Name: ", "Fahrenheit 451"],
		nameAuthor 	: ["Author: ", "Ray Bradbury"],
		isbnNumber 	: ["ISBN: ", "9789745171067"],
		dateAdded 	: ["Added: ", "12-27-1988"],
		datePublish : ["Published: ", "1953"],
		genre		: ["Genre: ", "science fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "10"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "AWESOME book."]
	},
	"book3": {
		nameBook 	: ["Name: ", "Grapes of Wrath"],
		nameAuthor 	: ["Author: ", "John Steinbeck"],
		isbnNumber 	: ["ISBN: ", "9781440637124"],
		dateAdded 	: ["Added: ", "11-01-1977"],
		datePublish : ["Published: ", "1939"],
		genre		: ["Genre: ", "novel"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "7"],
		purchased	: ["Purchased: ", "borrowed"],
		cover		: ["Cover: ", "hardcover"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Better than I thought."]
	},
	"book4": {
		nameBook 	: ["Name: ", "The Long Winter"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "0064400069"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1971"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book5": {
		nameBook 	: ["Name: ", "These Happy Golden Years"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "0064400085"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1971"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book6": {
		nameBook 	: ["Name: ", "The First Four Years"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "006440031X"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1971"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book7": {
		nameBook 	: ["Name: ", "Little Town on the Prairie"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "0064400077"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1969"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book8": {
		nameBook 	: ["Name: ", "Little House in the Big Woods"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "006440031X"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1971"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book9": {
		nameBook 	: ["Name: ", "Little House on the Prairie"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "9780061958274"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1963"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book10": {
		nameBook 	: ["Name: ", "Farmer Boy"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "006026425X"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1953"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book11": {
		nameBook 	: ["Name: ", "On the Banks of Plum Creek"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "0060581832"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1971"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book12": {
		nameBook 	: ["Name: ", "By the Shores of Silver Lake"],
		nameAuthor 	: ["Author: ", "Laura Ingalls Wilder"],
		isbnNumber 	: ["ISBN: ", "0064400050"],
		dateAdded 	: ["Added: ", "08-19-1977"],
		datePublish : ["Published: ", "1971"],
		genre		: ["Genre: ", "historical fiction"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book13": {
		nameBook 	: ["Name: ", "Harry Potter and the Sorcerer's Stone"],
		nameAuthor 	: ["Author: ", "J.K. Rowling"],
		isbnNumber 	: ["ISBN: ", "059035342X"],
		dateAdded 	: ["Added: ", "06-13-2012"],
		datePublish : ["Published: ", "1997"],
		genre		: ["Genre: ", "fantasy"],
		readBook	: ["Read: ", "unread"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "hardcover"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Can't Wait to read this!"]
	},
	"book14": {
		nameBook 	: ["Name: ", "Harry Potter and the Chamber of Secrets"],
		nameAuthor 	: ["Author: ", "J.K. Rowling"],
		isbnNumber 	: ["ISBN: ", "0439064872"],
		dateAdded 	: ["Added: ", "06-13-2012"],
		datePublish : ["Published: ", "1998"],
		genre		: ["Genre: ", "fantasy"],
		readBook	: ["Read: ", "unread"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "hardcover"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Can't Wait to read this!"]
	},
	"book15": {
		nameBook 	: ["Name: ", "Harry Potter and the Prisoner of Azkaban"],
		nameAuthor 	: ["Author: ", "J.K. Rowling"],
		isbnNumber 	: ["ISBN: ", "9780439136365"],
		dateAdded 	: ["Added: ", "06-13-2012"],
		datePublish : ["Published: ", "1999"],
		genre		: ["Genre: ", "fantasy"],
		readBook	: ["Read: ", "unread"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "hardcover"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Can't Wait to read this!"]
	},
	"book16": {
		nameBook 	: ["Name: ", "Harry Potter and the Goblet of Fire"],
		nameAuthor 	: ["Author: ", "J.K. Rowling"],
		isbnNumber 	: ["ISBN: ", "9780439139601"],
		dateAdded 	: ["Added: ", "06-13-2012"],
		datePublish : ["Published: ", "2000"],
		genre		: ["Genre: ", "fantasy"],
		readBook	: ["Read: ", "unread"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "hardcover"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Can't Wait to read this!"]
	},
	"book17": {
		nameBook 	: ["Name: ", "Harry Potter and the Order of the Phoenix"],
		nameAuthor 	: ["Author: ", "J.K. Rowling"],
		isbnNumber 	: ["ISBN: ", "0439358078"],
		dateAdded 	: ["Added: ", "06-13-2012"],
		datePublish : ["Published: ", "2003"],
		genre		: ["Genre: ", "fantasy"],
		readBook	: ["Read: ", "unread"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "hardcover"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Can't Wait to read this!"]
	},
	"book18": {
		nameBook 	: ["Name: ", "Harry Potter and the Half-blood Prince"],
		nameAuthor 	: ["Author: ", "J.K. Rowling"],
		isbnNumber 	: ["ISBN: ", "0439785960"],
		dateAdded 	: ["Added: ", "06-13-2012"],
		datePublish : ["Published: ", "2006"],
		genre		: ["Genre: ", "fantasy"],
		readBook	: ["Read: ", "unread"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "hardcover"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Can't Wait to read this!"]
	},
	"book19": {
		nameBook 	: ["Name: ", "Harry Potter and the Deathly Hollows"],
		nameAuthor 	: ["Author: ", "J.K. Rowling"],
		isbnNumber 	: ["ISBN: ", "0545139708"],
		dateAdded 	: ["Added: ", "06-13-2012"],
		datePublish : ["Published: ", "2009"],
		genre		: ["Genre: ", "fantasy"],
		readBook	: ["Read: ", "unread"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "hardcover"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Can't Wait to read this!"]
	},
	"book20": {
		nameBook 	: ["Name: ", "Twilight"],
		nameAuthor 	: ["Author: ", "Stephanie Meyers"],
		isbnNumber 	: ["ISBN: ", "0316160172"],
		dateAdded 	: ["Added: ", "08-13-2012"],
		datePublish : ["Published: ", "2005"],
		genre		: ["Genre: ", "drama"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book21": {
		nameBook 	: ["Name: ", "New Moon"],
		nameAuthor 	: ["Author: ", "Stephanie Meyers"],
		isbnNumber 	: ["ISBN: ", "0316160199"],
		dateAdded 	: ["Added: ", "08-13-2012"],
		datePublish : ["Published: ", "2006"],
		genre		: ["Genre: ", "drama"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book22": {
		nameBook 	: ["Name: ", "Eclipse"],
		nameAuthor 	: ["Author: ", "Stephanie Meyers"],
		isbnNumber 	: ["ISBN: ", "0316160202"],
		dateAdded 	: ["Added: ", "08-13-2012"],
		datePublish : ["Published: ", "2007"],
		genre		: ["Genre: ", "drama"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	},
	"book23": {
		nameBook 	: ["Name: ", "Breaking Dawn"],
		nameAuthor 	: ["Author: ", "Stephanie Meyers"],
		isbnNumber 	: ["ISBN: ", "9780316067928"],
		dateAdded 	: ["Added: ", "08-13-2012"],
		datePublish : ["Published: ", "2008"],
		genre		: ["Genre: ", "drama"],
		readBook	: ["Read: ", "read"],
		rating		: ["Rate: ", "6"],
		purchased	: ["Purchased: ", "purchased"],
		cover		: ["Cover: ", "paperback"],
		fiction		: ["Type: ", "fiction"],
		comments 	: ["Comments: ", "Great book."]
	}
}